import { useEffect, useMemo, useState } from 'react';
import { ScrollView, Text, View } from 'react-native';
import { CalendarCheck } from 'lucide-react-native';
import { useAuth } from '@/context/AuthContext';
import { useParentMobile } from '@/context/ParentMobileContext';
import { supabase } from '@/lib/supabase';
import type { Attendance } from '@/lib/types';
import { Card, Empty, Loading } from '@/components/ui';
import { formatDate } from '@/lib/format';
import { colors, styles } from '@/theme';

export default function ParentAttendance() { const { profile } = useAuth(); const { selectedChild, loading } = useParentMobile(); const [records, setRecords] = useState<Attendance[]>([]); const [fetching, setFetching] = useState(true); useEffect(() => { if (!selectedChild || !profile?.school_id) return; (async () => { setFetching(true); const { data } = await supabase.from('attendance').select('*').eq('school_id', profile.school_id).eq('student_id', selectedChild.id).order('date', { ascending: false }).limit(60); setRecords((data as Attendance[]) ?? []); setFetching(false); })(); }, [selectedChild, profile?.school_id]); const present = records.filter((x) => ['present', 'late'].includes(x.status)).length; const pct = records.length ? Math.round(present / records.length * 100) : 0; const byDate = useMemo(() => [...new Set(records.map((x) => x.date))], [records]); if (loading || fetching) return <Loading />; return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>Student wellbeing</Text><Text style={styles.title}>Attendance</Text><Text style={styles.subtitle}>{selectedChild?.full_name ?? 'Select a child'} · {pct}% attendance</Text><Card style={{ marginTop: 20 }}><View style={styles.row}><CalendarCheck color={colors.success} size={24} /><View style={{ marginLeft: 12 }}><Text style={styles.label}>Overall attendance</Text><Text style={{ fontSize: 28, fontWeight: '800', color: colors.success }}>{pct}%</Text></View></View></Card><Text style={styles.sectionTitle}>Recent days</Text>{!selectedChild || !records.length ? <Card><Empty title="No attendance recorded" body="Attendance records will appear here once the school marks them." /></Card> : byDate.map((date) => { const day = records.filter((x) => x.date === date); return <Card key={date}><View style={styles.row}><View style={{ flex: 1 }}><Text style={{ fontWeight: '700', color: colors.ink }}>{formatDate(date)}</Text><Text style={{ color: colors.muted, marginTop: 4 }}>{day.map((x) => `${x.session}: ${x.status}`).join(' · ')}</Text></View><View style={{ backgroundColor: day.every((x) => ['present', 'late'].includes(x.status)) ? colors.successSoft : colors.errorSoft, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 6 }}><Text style={{ color: day.every((x) => ['present', 'late'].includes(x.status)) ? colors.success : colors.error, fontWeight: '700' }}>{day.every((x) => ['present', 'late'].includes(x.status)) ? 'Present' : 'Review'}</Text></View></View></Card>; })}</ScrollView>; }
