import { useEffect, useMemo, useState } from 'react';
import { ScrollView, Text, View } from 'react-native';
import { BookOpen, CalendarClock } from 'lucide-react-native';
import { useAuth } from '@/context/AuthContext';
import { useParentMobile } from '@/context/ParentMobileContext';
import { supabase } from '@/lib/supabase';
import type { Homework } from '@/lib/types';
import { Card, Empty, Loading } from '@/components/ui';
import { formatDate } from '@/lib/format';
import { colors, styles } from '@/theme';

export default function ParentHomework() { const { profile } = useAuth(); const { selectedChild, loading } = useParentMobile(); const [items, setItems] = useState<Homework[]>([]); const [fetching, setFetching] = useState(true); useEffect(() => { if (!selectedChild?.class_id || !profile?.school_id) return; (async () => { setFetching(true); const { data } = await supabase.from('homework').select('*').eq('school_id', profile.school_id).eq('class_id', selectedChild.class_id).order('due_date', { ascending: true }); setItems((data as Homework[]) ?? []); setFetching(false); })(); }, [selectedChild, profile?.school_id]); const overdue = useMemo(() => items.filter((x) => new Date(x.due_date) < new Date()).length, [items]); if (loading || fetching) return <Loading />; return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>{selectedChild?.full_name ?? 'Student'}</Text><Text style={styles.title}>Homework</Text><Text style={styles.subtitle}>{items.length} assignments · {overdue} overdue</Text><View style={{ marginTop: 20 }}>{!items.length ? <Card><Empty title="No homework yet" body="Assignments for your child’s class will appear here." /></Card> : items.map((item) => { const isOverdue = new Date(item.due_date) < new Date(); return <Card key={item.id} style={isOverdue ? { borderColor: '#fecaca', backgroundColor: '#fffafa' } : undefined}><View style={styles.row}><View style={{ width: 42, height: 42, borderRadius: 13, backgroundColor: isOverdue ? colors.errorSoft : colors.primarySoft, justifyContent: 'center', alignItems: 'center' }}><BookOpen color={isOverdue ? colors.error : colors.primary} size={21} /></View><View style={{ flex: 1, marginLeft: 12 }}><Text style={{ color: colors.ink, fontWeight: '700', fontSize: 16 }}>{item.title}</Text><Text style={{ color: isOverdue ? colors.error : colors.muted, marginTop: 5 }}>Due {formatDate(item.due_date)}</Text></View><CalendarClock color={colors.muted} size={18} /></View>{item.description ? <Text style={{ color: colors.muted, lineHeight: 20, marginTop: 14 }}>{item.description}</Text> : null}</Card>; })}</View></ScrollView>; }
