import { useEffect, useState } from 'react';
import { ScrollView, Text } from 'react-native';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import type { ClassRow, Student } from '@/lib/types';
import { Card, Empty, Loading } from '@/components/ui';
import { colors, styles } from '@/theme';

export default function TeacherClasses() { const { profile } = useAuth(); const [classes, setClasses] = useState<ClassRow[]>([]); const [students, setStudents] = useState<Student[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { if (!profile?.school_id) return; (async () => { const [c, s] = await Promise.all([supabase.from('classes').select('*').eq('school_id', profile.school_id).eq('class_teacher_id', profile.id).order('name'), supabase.from('students').select('*').eq('school_id', profile.school_id).order('full_name')]); setClasses((c.data as ClassRow[]) ?? []); setStudents((s.data as Student[]) ?? []); setLoading(false); })(); }, [profile?.school_id, profile?.id]); if (loading) return <Loading />; return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>Teaching workspace</Text><Text style={styles.title}>Classes</Text><Text style={styles.subtitle}>Your assigned classes and students.</Text>{!classes.length ? <Card><Empty title="No classes assigned" body="Your assigned classes will appear here." /></Card> : classes.map((item) => <Card key={item.id}><Text style={{ fontSize: 18, fontWeight: '800', color: colors.ink }}>{item.name}</Text><Text style={{ color: colors.muted, marginTop: 5 }}>{students.filter((x) => x.class_id === item.id).length} students · {item.grade_level ?? 'Class'}</Text><Text style={{ color: colors.primary, fontWeight: '700', marginTop: 14 }}>Student list</Text>{students.filter((x) => x.class_id === item.id).slice(0, 8).map((student) => <Text key={student.id} style={{ color: colors.ink, paddingTop: 10 }}>{student.full_name}</Text>)}</Card>)}</ScrollView>; }
