import { useEffect, useState } from 'react';
import { ScrollView, Text, View } from 'react-native';
import { BookOpen, CalendarCheck, Users } from 'lucide-react-native';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import type { ClassRow, Student } from '@/lib/types';
import { Card, Loading } from '@/components/ui';
import { colors, styles } from '@/theme';

export default function TeacherHome() { const { profile, school } = useAuth(); const [classes, setClasses] = useState<ClassRow[]>([]); const [students, setStudents] = useState<Student[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { if (!profile?.school_id || !profile.id) return; (async () => { const [classRes, studentRes] = await Promise.all([supabase.from('classes').select('*').eq('school_id', profile.school_id).eq('class_teacher_id', profile.id), supabase.from('students').select('*').eq('school_id', profile.school_id)]); setClasses((classRes.data as ClassRow[]) ?? []); setStudents((studentRes.data as Student[]) ?? []); setLoading(false); })(); }, [profile?.school_id, profile?.id]); if (loading) return <Loading />; return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>{school?.name ?? 'EduBridge'}</Text><Text style={styles.title}>Good morning, {profile?.full_name?.split(' ')[0] ?? 'Teacher'}</Text><Text style={styles.subtitle}>Your teaching day at a glance.</Text><View style={{ flexDirection: 'row', gap: 12, marginTop: 20 }}><Card style={{ flex: 1 }}><Users color={colors.primary} size={22} /><Text style={{ fontSize: 28, fontWeight: '800', color: colors.ink, marginTop: 12 }}>{students.length}</Text><Text style={{ color: colors.muted }}>Students</Text></Card><Card style={{ flex: 1 }}><BookOpen color={colors.primary} size={22} /><Text style={{ fontSize: 28, fontWeight: '800', color: colors.ink, marginTop: 12 }}>{classes.length}</Text><Text style={{ color: colors.muted }}>My classes</Text></Card></View><Card style={{ marginTop: 4 }}><View style={styles.row}><CalendarCheck color={colors.success} size={22} /><View style={{ marginLeft: 12 }}><Text style={{ fontWeight: '700', color: colors.ink }}>Keep attendance up to date</Text><Text style={{ color: colors.muted, marginTop: 4 }}>Mark today’s attendance from the Attendance tab.</Text></View></View></Card><Text style={styles.sectionTitle}>My classes</Text>{classes.map((item) => <Card key={item.id}><Text style={{ fontWeight: '700', color: colors.ink, fontSize: 16 }}>{item.name}</Text><Text style={{ color: colors.muted, marginTop: 5 }}>{item.grade_level ?? 'Class'} · {item.stream ?? 'All students'}</Text></Card>)}</ScrollView>; }
